package br.com.ativ09InterfaceGrafica;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class CadCarga extends javax.swing.JFrame {
    private static CadCarga cadCargUnic;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CadCarga.class.getName());

    /**
     * Creates new form CadVeicPasseio
     */
    public CadCarga() {
        initComponents();
    }
    public static CadCarga geraCadCarg(){
        if(cadCargUnic == null){
            cadCargUnic = new CadCarga();
        }
        return cadCargUnic;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mnVeicPasseio = new javax.swing.JMenu();
        rtTara = new java.awt.Label();
        cxTara = new java.awt.TextField();
        rtPlaca = new java.awt.Label();
        cxPlaca = new java.awt.TextField();
        rtMarca = new java.awt.Label();
        cxMarca = new java.awt.TextField();
        rtModelo = new java.awt.Label();
        cxModelo = new java.awt.TextField();
        rtCor = new java.awt.Label();
        cxCor = new java.awt.TextField();
        rtQtdRodas = new java.awt.Label();
        cxQtdRodas = new java.awt.TextField();
        rtVelocMax = new java.awt.Label();
        cxVelocMax = new java.awt.TextField();
        rtQtdPistoes = new java.awt.Label();
        cxQtdPistoes = new java.awt.TextField();
        rtPotencia = new java.awt.Label();
        cxPotencia = new java.awt.TextField();
        btCadastrar = new java.awt.Button();
        btLimpar = new java.awt.Button();
        btConsultar = new java.awt.Button();
        btSair = new java.awt.Button();
        rtCargaMax = new java.awt.Label();
        cxCargaMax = new java.awt.TextField();
        btImprimir = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbVeicCarga = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();

        mnVeicPasseio.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Carga");

        rtTara.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        rtTara.setText("Tara:");

        rtPlaca.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        rtPlaca.setText("Placa:");

        rtMarca.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        rtMarca.setText("Marca:");

        rtModelo.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        rtModelo.setText("Modelo:");

        rtCor.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        rtCor.setText("Cor:");

        rtQtdRodas.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        rtQtdRodas.setText("Qtd.Rodas:");

        rtVelocMax.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        rtVelocMax.setText("Velocidade Max:");

        cxVelocMax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxVelocMaxActionPerformed(evt);
            }
        });
        cxVelocMax.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cxVelocMaxKeyPressed(evt);
            }
        });

        rtQtdPistoes.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        rtQtdPistoes.setText("Qtd.Pistoes:");

        rtPotencia.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        rtPotencia.setText("Potencia:");

        btCadastrar.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btCadastrar.setLabel("Cadastrar");
        btCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastrarActionPerformed(evt);
            }
        });

        btLimpar.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btLimpar.setLabel("Limpar");
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });

        btConsultar.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btConsultar.setLabel("Consultar...");
        btConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsultarActionPerformed(evt);
            }
        });

        btSair.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btSair.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btSair.setLabel("Sair");
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        rtCargaMax.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        rtCargaMax.setText("Carga Max:");

        btImprimir.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btImprimir.setText("Imprimir Todos");
        btImprimir.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btImprimirActionPerformed(evt);
            }
        });

        btExcluir.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btExcluir.setText("Excluir");
        btExcluir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });

        tbVeicCarga.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tara", "Carga Max", "Placa", "Marca", "Modelo", "Cor", "Qtd.Rodas", "Veloc.Max", "Qtd.Pistoes", "Potencia"
            }
        ));
        jScrollPane1.setViewportView(tbVeicCarga);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rtCor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cxCor, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(rtQtdRodas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rtTara, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(23, 23, 23)
                                .addComponent(cxTara, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(rtCargaMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cxCargaMax, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(25, 25, 25)
                                .addComponent(rtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)
                                .addComponent(cxPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(52, 52, 52)
                                        .addComponent(cxMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(rtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(32, 32, 32)
                                .addComponent(rtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cxModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cxQtdRodas, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(22, 22, 22)
                                .addComponent(rtVelocMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cxVelocMax, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(rtQtdPistoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cxQtdPistoes, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(rtPotencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cxPotencia, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(123, 123, 123))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 1, Short.MAX_VALUE)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 854, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btSair, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(104, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cxTara, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(cxCargaMax, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(rtTara, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(rtPlaca, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cxPlaca, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(rtMarca, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cxMarca, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(rtModelo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(rtCargaMax, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cxModelo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rtQtdRodas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cxQtdRodas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rtVelocMax, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cxVelocMax, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rtCor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cxCor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rtQtdPistoes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cxQtdPistoes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rtPotencia, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cxPotencia, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btLimpar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btConsultar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btCadastrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btSair, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(btExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastrarActionPerformed
        // TODO add your handling code here:
        cadastrar();
    }//GEN-LAST:event_btCadastrarActionPerformed

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btSairActionPerformed

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        // TODO add your handling code here:
        limpar();
    }//GEN-LAST:event_btLimparActionPerformed

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        // TODO add your handling code here:
       excluir();
    }//GEN-LAST:event_btExcluirActionPerformed

    private void btConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsultarActionPerformed
        // TODO add your handling code here:
        consultar();
    }//GEN-LAST:event_btConsultarActionPerformed

    private void btImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btImprimirActionPerformed
        // TODO add your handling code here:
        imprimir();
    }//GEN-LAST:event_btImprimirActionPerformed

    private void cxVelocMaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxVelocMaxActionPerformed
        // TODO add your handling code here:
        // A regra é: menor que 80 OU maior que 110.
        String veloc1 = cxVelocMax.getText();
        if (Integer.parseInt(veloc1) < 80 || Integer.parseInt(veloc1) > 110) {
            System.out.println("Velocidade nao permitida");
        }
    }//GEN-LAST:event_cxVelocMaxActionPerformed

    private void cxVelocMaxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cxVelocMaxKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxVelocMaxKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CadCarga().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button btCadastrar;
    private java.awt.Button btConsultar;
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btImprimir;
    private java.awt.Button btLimpar;
    private java.awt.Button btSair;
    private java.awt.TextField cxCargaMax;
    private java.awt.TextField cxCor;
    private java.awt.TextField cxMarca;
    private java.awt.TextField cxModelo;
    private java.awt.TextField cxPlaca;
    private java.awt.TextField cxPotencia;
    private java.awt.TextField cxQtdPistoes;
    private java.awt.TextField cxQtdRodas;
    private java.awt.TextField cxTara;
    private java.awt.TextField cxVelocMax;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JMenu mnVeicPasseio;
    private java.awt.Label rtCargaMax;
    private java.awt.Label rtCor;
    private java.awt.Label rtMarca;
    private java.awt.Label rtModelo;
    private java.awt.Label rtPlaca;
    private java.awt.Label rtPotencia;
    private java.awt.Label rtQtdPistoes;
    private java.awt.Label rtQtdRodas;
    private java.awt.Label rtTara;
    private java.awt.Label rtVelocMax;
    private javax.swing.JTable tbVeicCarga;
    // End of variables declaration//GEN-END:variables

    
     private void limpar() {
        cxTara.setText("");
        cxCargaMax.setText("");
        cxCor.setText("");
        cxMarca.setText("");
        cxModelo.setText("");
        cxPlaca.setText("");
        cxPotencia.setText("");
        cxQtdPistoes.setText("");
        cxQtdRodas.setText("");
        cxVelocMax.setText("");
        
    }

    private void imprimir() {
                // TODO add your handling code here:
        int linhaSelecionada = tbVeicCarga.getSelectedRow();
        if (linhaSelecionada == -1) {
            JOptionPane.showMessageDialog(this, "Selecione uma Placa(linha) na tabela para consultar.");
            return;
        }
            // Exibir os dados da tabela em um JOptionPane
        if (tbVeicCarga.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this, "Não há dados para mostrar.");
            return;
        }
        String tara = tbVeicCarga.getValueAt(linhaSelecionada, 0).toString();
        StringBuilder dados = new StringBuilder("Relatório de Dados:\n\n");

        for (int i = 0; i < tbVeicCarga.getRowCount(); i++) {
            for (int j = 0; j < tbVeicCarga.getColumnCount(); j++) {
                dados.append(tbVeicCarga.getColumnName(j))
                        .append(": ")
                        .append(tbVeicCarga.getValueAt(i, j))
                        .append("\n   ");
            }
            dados.append("\n");
        }
        JOptionPane.showMessageDialog(this, dados.toString(), "Relatório", JOptionPane.INFORMATION_MESSAGE);
    
    }

    private void consultar() {
                      int linhaSelecionada = tbVeicCarga.getSelectedRow();

        if (linhaSelecionada == -1) {
            JOptionPane.showMessageDialog(this, "Selecione uma Placa(linha) na tabela para consultar.");
            return;
        }
        // Recupera os dados da linha selecionada
        String tara = tbVeicCarga.getValueAt(linhaSelecionada, 0).toString();
        String cargaMax = tbVeicCarga.getValueAt(linhaSelecionada, 0).toString();
        String placa = tbVeicCarga.getValueAt(linhaSelecionada, 1).toString();
        String marca = tbVeicCarga.getValueAt(linhaSelecionada, 2).toString();
        String modelo = tbVeicCarga.getValueAt(linhaSelecionada, 3).toString();
        String cor = tbVeicCarga.getValueAt(linhaSelecionada, 4).toString();
        String qtdRodas = tbVeicCarga.getValueAt(linhaSelecionada, 5).toString();
        String velocMax = tbVeicCarga.getValueAt(linhaSelecionada, 6).toString();
        String qtdPistoes = tbVeicCarga.getValueAt(linhaSelecionada, 7).toString();
        String potencia = tbVeicCarga.getValueAt(linhaSelecionada, 8).toString();

        // Exibe os dados em um JOptionPane ou em outra tela
        String mensagem = "Dados do Veículo:\n"
                + "Tara: " + tara + "\n"
                + "Carga Max: " + cargaMax + "\n"
                + "Placa: " + placa + "\n"
                + "Marca: " + marca + "\n"
                + "Modelo: " + modelo + "\n"
                + "Cor: " + cor + "\n"
                + "Qtd Rodas: " + qtdRodas + "\n"
                + "Velocidade Máx: " + velocMax + "\n"
                + "Qtd Pistões: " + qtdPistoes + "\n"
                + "Potência: " + potencia;

        JOptionPane.showMessageDialog(this, mensagem, "Consulta", JOptionPane.INFORMATION_MESSAGE);
    }

    private void excluir() {
         // TODO add your handling code here:
        int linhaSelecionada = tbVeicCarga.getSelectedRow();
        if (linhaSelecionada == -1) {
            JOptionPane.showMessageDialog(this, "Selecione uma linha");
        } else {
            DefaultTableModel tabelaVeicCarg = (DefaultTableModel) tbVeicCarga.getModel();
            tabelaVeicCarg.removeRow(linhaSelecionada);
            JOptionPane.showMessageDialog(this, "Veiculo Carga excluido...");
        }
    }

    private void cadastrar() {
        int tara = Integer.parseInt(cxTara.getText());
        int cargaMax = Integer.parseInt(cxCargaMax.getText());
        String placa = cxPlaca.getText();
        String marca = cxMarca.getText();
        String modelo = cxModelo.getText();
        String cor = cxCor.getText();
        int qtdRodas = Integer.parseInt(cxQtdRodas.getText());
        int velocMax = Integer.parseInt(cxVelocMax.getText());
        int qtdPistoes = Integer.parseInt(cxQtdPistoes.getText());
        int potencia = Integer.parseInt(cxPotencia.getText());
        //incluindo dados para tabela JTable
        DefaultTableModel  tabelaVeicCarga = (DefaultTableModel)tbVeicCarga.getModel();
        
        Object[] novoVeicCarga = new Object[]{
            tara,
            cargaMax,
            placa,
            marca,
            modelo,
            cor,
            qtdRodas,
            velocMax,
            qtdPistoes,
            potencia
        };
            tabelaVeicCarga.addRow(novoVeicCarga);
            //limpar campos
            cxTara.setText("");
            cxCargaMax.setText("");
            cxPlaca.setText("");
            cxMarca.setText("");
            cxModelo.setText("");
            cxCor.setText("");
            cxQtdRodas.setText("");
            cxVelocMax.setText("");
            cxQtdPistoes.setText("");
            cxPotencia.setText("");
            }
}
