package br.com.ativ09InterfaceGrafica;

import java.awt.*;
import java.awt.print.PrinterException;
import java.text.MessageFormat;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

public class CadPasseios extends javax.swing.JFrame {
    private static CadPasseios cadPasUnic;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CadPasseios.class.getName());

    private static void EXIT_ON_CLOSE() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    static void DISPOSE_ON_CLOSE() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * Creates new form CadVeicPasseio
     */
    CadPasseios() {
        initComponents();
    }
    
    public static CadPasseios geraCadPass(){
        if(cadPasUnic == null){
            cadPasUnic = new CadPasseios();
        }
        return cadPasUnic;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mnVeicPasseio = new javax.swing.JMenu();
        rtQtdPassageiros = new java.awt.Label();
        cxQtdPassageiros = new java.awt.TextField();
        rtPlaca = new java.awt.Label();
        cxPlaca = new java.awt.TextField();
        rtMarca = new java.awt.Label();
        cxMarca = new java.awt.TextField();
        rtModelo = new java.awt.Label();
        cxModelo = new java.awt.TextField();
        rtCor = new java.awt.Label();
        cxCor = new java.awt.TextField();
        rtQtdRodas = new java.awt.Label();
        cxQtdRodas = new java.awt.TextField();
        rtVelocMax = new java.awt.Label();
        cxVelocMax = new java.awt.TextField();
        rtQtdPistoes = new java.awt.Label();
        cxQtdPistoes = new java.awt.TextField();
        rtPotencia = new java.awt.Label();
        cxPotencia = new java.awt.TextField();
        btCadVeicPas = new java.awt.Button();
        btLimparVeicPas = new java.awt.Button();
        btConsultar = new java.awt.Button();
        btSairVeicPas = new java.awt.Button();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbVeicPass = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        btImprimir = new java.awt.Button();
        btExcluir = new java.awt.Button();

        mnVeicPasseio.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Passeios");

        rtQtdPassageiros.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        rtQtdPassageiros.setText("Qtd.Passageiros:");

        rtPlaca.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        rtPlaca.setText("Placa:");

        rtMarca.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        rtMarca.setText("Marca:");

        cxMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxMarcaActionPerformed(evt);
            }
        });

        rtModelo.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        rtModelo.setText("Modelo:");

        rtCor.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        rtCor.setText("Cor:");

        rtQtdRodas.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        rtQtdRodas.setText("Qtd.Rodas:");

        rtVelocMax.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        rtVelocMax.setText("Velocidade Max:");

        rtQtdPistoes.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        rtQtdPistoes.setText("Qtd.Pistoes:");

        rtPotencia.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        rtPotencia.setText("Potencia:");

        btCadVeicPas.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btCadVeicPas.setLabel("Cadastrar");
        btCadVeicPas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadVeicPasActionPerformed(evt);
            }
        });

        btLimparVeicPas.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btLimparVeicPas.setLabel("Limpar");
        btLimparVeicPas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparVeicPasActionPerformed(evt);
            }
        });

        btConsultar.setActionCommand("Consultar");
        btConsultar.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btConsultar.setLabel("Consultar");
        btConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsultarActionPerformed(evt);
            }
        });

        btSairVeicPas.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btSairVeicPas.setLabel("Sair");
        btSairVeicPas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairVeicPasActionPerformed(evt);
            }
        });

        tbVeicPass.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Qtd.Passageiros", "Placa", "Marca", "Modelo", "Cor", "Qtd.Rodas", "Veloc.Max", "Qtd.Pistoes", "Potencia"
            }
        ));
        jScrollPane1.setViewportView(tbVeicPass);

        btImprimir.setActionCommand("Imprimir");
        btImprimir.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btImprimir.setLabel("Imprimir Todos");
        btImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btImprimirActionPerformed(evt);
            }
        });

        btExcluir.setActionCommand("Excluir");
        btExcluir.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btExcluir.setLabel("Excluir");
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rtQtdRodas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cxQtdRodas, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rtVelocMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cxVelocMax, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rtQtdPistoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cxQtdPistoes, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rtPotencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(cxPotencia, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator2)
                            .addComponent(jSeparator1)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(rtQtdPassageiros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cxQtdPassageiros, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(19, 19, 19)
                                        .addComponent(rtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cxPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(rtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cxMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(17, 17, 17)
                                        .addComponent(rtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cxModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btCadVeicPas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btLimparVeicPas, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btSairVeicPas, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(rtCor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cxCor, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)))
                        .addGap(24, 24, 24))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cxQtdPassageiros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rtQtdPassageiros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cxPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cxMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cxModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rtCor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cxCor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cxPotencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rtQtdRodas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cxQtdRodas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rtVelocMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cxVelocMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rtQtdPistoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cxQtdPistoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rtPotencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btCadVeicPas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btLimparVeicPas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btSairVeicPas, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btCadVeicPasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadVeicPasActionPerformed
        // TODO add your handling code here:
        //primeiro, recuperar os dados no form.
        int qtdPassageiros = Integer.parseInt(cxQtdPassageiros.getText());
        String placa = cxPlaca.getText();
        String marca = cxMarca.getText();
        String modelo = cxModelo.getText();
        String cor = cxCor.getText();
        int qtdRodas = Integer.parseInt(cxQtdRodas.getText());
        int velocMax = Integer.parseInt(cxVelocMax.getText());
        int qtdPistoes = Integer.parseInt(cxQtdPistoes.getText());
        int potencia = Integer.parseInt(cxPotencia.getText());
        //incluindo dados para tabela JTable
        DefaultTableModel  tabelaVeicPass = (DefaultTableModel)tbVeicPass.getModel();
        
        Object[] novoVeicPass = new Object[]{
            qtdPassageiros,
            placa,
            marca,
            modelo,
            cor,
            qtdRodas,
            velocMax,
            qtdPistoes,
            potencia
        };
            tabelaVeicPass.addRow(novoVeicPass);
            
            //limpar campos
            cxQtdPassageiros.setText("");
            cxPlaca.setText("");
            cxMarca.setText("");
            cxModelo.setText("");
            cxCor.setText("");
            cxQtdRodas.setText("");
            cxVelocMax.setText("");
            cxQtdPistoes.setText("");
            cxPotencia.setText("");
            
        
       
    }//GEN-LAST:event_btCadVeicPasActionPerformed

    private void btLimparVeicPasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparVeicPasActionPerformed
        // TODO add your handling code here:
        limpar();
    }//GEN-LAST:event_btLimparVeicPasActionPerformed

    private void btSairVeicPasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairVeicPasActionPerformed
        // TODO add your handling code here:
         this.dispose();
    }//GEN-LAST:event_btSairVeicPasActionPerformed

    private void cxMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxMarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxMarcaActionPerformed

    private void btConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsultarActionPerformed
        // TODO add your handling code here:

        int linhaSelecionada = tbVeicPass.getSelectedRow();

        if (linhaSelecionada == -1) {
            JOptionPane.showMessageDialog(this, "Selecione uma Placa(linha) na tabela para consultar.");
            return;
        }

        // Recupera os dados da linha selecionada
        String qtdPassageiros = tbVeicPass.getValueAt(linhaSelecionada, 0).toString();
        String placa = tbVeicPass.getValueAt(linhaSelecionada, 1).toString();
        String marca = tbVeicPass.getValueAt(linhaSelecionada, 2).toString();
        String modelo = tbVeicPass.getValueAt(linhaSelecionada, 3).toString();
        String cor = tbVeicPass.getValueAt(linhaSelecionada, 4).toString();
        String qtdRodas = tbVeicPass.getValueAt(linhaSelecionada, 5).toString();
        String velocMax = tbVeicPass.getValueAt(linhaSelecionada, 6).toString();
        String qtdPistoes = tbVeicPass.getValueAt(linhaSelecionada, 7).toString();
        String potencia = tbVeicPass.getValueAt(linhaSelecionada, 8).toString();

        // Exibe os dados em um JOptionPane ou em outra tela
        String mensagem = "Dados do Veículo:\n"
                + "Placa: " + placa + "\n"
                + "Marca: " + marca + "\n"
                + "Modelo: " + modelo + "\n"
                + "Cor: " + cor + "\n"
                + "Qtd Passageiros: " + qtdPassageiros + "\n"
                + "Qtd Rodas: " + qtdRodas + "\n"
                + "Velocidade Máx: " + velocMax + "\n"
                + "Qtd Pistões: " + qtdPistoes + "\n"
                + "Potência: " + potencia;

        JOptionPane.showMessageDialog(this, mensagem, "Consulta", JOptionPane.INFORMATION_MESSAGE);

    }//GEN-LAST:event_btConsultarActionPerformed

    private void btImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btImprimirActionPerformed
        // TODO add your handling code here:
        int linhaSelecionada = tbVeicPass.getSelectedRow();
        if (linhaSelecionada == -1) {
            JOptionPane.showMessageDialog(this, "Selecione uma Placa(linha) na tabela para consultar.");
            return;
        }
            // Exibir os dados da tabela em um JOptionPane
        if (tbVeicPass.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this, "Não há dados para mostrar.");
            return;
        }
        String qtdPassageiros = tbVeicPass.getValueAt(linhaSelecionada, 0).toString();
        StringBuilder dados = new StringBuilder("Relatório de Dados:\n\n");

        for (int i = 0; i < tbVeicPass.getRowCount(); i++) {
            for (int j = 0; j < tbVeicPass.getColumnCount(); j++) {
                dados.append(tbVeicPass.getColumnName(j))
                        .append(": ")
                        .append(tbVeicPass.getValueAt(i, j))
                        .append("\n   ");
            }
            dados.append("\n");
        }

        JOptionPane.showMessageDialog(this, dados.toString(), "Relatório", JOptionPane.INFORMATION_MESSAGE);


    }//GEN-LAST:event_btImprimirActionPerformed

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        // TODO add your handling code here:
        int linhaSelecionada = tbVeicPass.getSelectedRow();
        if (linhaSelecionada == -1) {
            JOptionPane.showMessageDialog(this, "Selecione uma linha");
        } else {
            DefaultTableModel tabelaVeicPass = (DefaultTableModel) tbVeicPass.getModel();
            tabelaVeicPass.removeRow(linhaSelecionada);
            JOptionPane.showMessageDialog(this, "Veiculo Passeeio excluido...");

        }
    }//GEN-LAST:event_btExcluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CadPasseios().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button btCadVeicPas;
    private java.awt.Button btConsultar;
    private java.awt.Button btExcluir;
    private java.awt.Button btImprimir;
    private java.awt.Button btLimparVeicPas;
    private java.awt.Button btSairVeicPas;
    private java.awt.TextField cxCor;
    private java.awt.TextField cxMarca;
    private java.awt.TextField cxModelo;
    private java.awt.TextField cxPlaca;
    private java.awt.TextField cxPotencia;
    private java.awt.TextField cxQtdPassageiros;
    private java.awt.TextField cxQtdPistoes;
    private java.awt.TextField cxQtdRodas;
    private java.awt.TextField cxVelocMax;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JMenu mnVeicPasseio;
    private java.awt.Label rtCor;
    private java.awt.Label rtMarca;
    private java.awt.Label rtModelo;
    private java.awt.Label rtPlaca;
    private java.awt.Label rtPotencia;
    private java.awt.Label rtQtdPassageiros;
    private java.awt.Label rtQtdPistoes;
    private java.awt.Label rtQtdRodas;
    private java.awt.Label rtVelocMax;
    private javax.swing.JTable tbVeicPass;
    // End of variables declaration//GEN-END:variables

    private void limpar() {
    cxCor.setText("");
    cxMarca.setText("");
    cxModelo.setText("");
    cxPlaca.setText("");
    cxPotencia.setText("");
    cxQtdPassageiros.setText("");
    cxQtdPistoes.setText("");
    cxQtdRodas.setText("");
    cxVelocMax.setText("");
        
    }

    private void sair() {
        CadPasseios.DISPOSE_ON_CLOSE();
    
    }

}

