/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ativ09InterfaceGrafica;

/**
 *
 * @author USER
 */
public class PrincipalGestaoVeiculos extends javax.swing.JFrame {
    private static PrincipalGestaoVeiculos cadPasPrinSecUnic;
    private static PrincipalGestaoVeiculos cadCargPrinSecUnic;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PrincipalGestaoVeiculos.class.getName());

    /**
     * Creates new form GestaoVeiculos
     */
    public PrincipalGestaoVeiculos() {
        initComponents();
    }
    
    public static PrincipalGestaoVeiculos geraCadSecPass(){
        if(cadPasPrinSecUnic == null){
            cadPasPrinSecUnic = new PrincipalGestaoVeiculos();
        }
        return cadPasPrinSecUnic;
    }

    public static PrincipalGestaoVeiculos geraCadSecCarg(){
        if(cadCargPrinSecUnic == null){
            cadCargPrinSecUnic = new PrincipalGestaoVeiculos();
        }
        return cadCargPrinSecUnic;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        btPasseio = new java.awt.Button();
        btCarga = new java.awt.Button();
        mnBarPasseio = new javax.swing.JMenuBar();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestao de Veiculos");

        btPasseio.setLabel("Passeio...");
        btPasseio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPasseioActionPerformed(evt);
            }
        });

        btCarga.setLabel("Carga...");
        btCarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCargaActionPerformed(evt);
            }
        });
        setJMenuBar(mnBarPasseio);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btPasseio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btCarga, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(189, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(btPasseio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btCarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(87, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btPasseioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPasseioActionPerformed
        //SecundariaVeicPasseio.geraCadSecPass().setVisible(true);     // TODO add your handling code here:
    }//GEN-LAST:event_btPasseioActionPerformed

    private void btCargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCargaActionPerformed
        //SecundarioVeicCarga.geraCadSecCarg().setVisible(true);       // TODO add your handling code here:
    }//GEN-LAST:event_btCargaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new PrincipalGestaoVeiculos().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button btCarga;
    private java.awt.Button btPasseio;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar mnBarPasseio;
    // End of variables declaration//GEN-END:variables
}
